spring.application.name: cache-study

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true


logging:
  level:
    org.springframework.cache.interceptor.CacheInterceptor: TRACE
    org.springframework.cache.interceptor.SimpleKeyGenerator: TRACE
    org.springframework.cache: DEBUG